server:
  port: 9010

spring:
  application:
    name: work-quill-server-base
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/work_quill_base
  sql:
    init:
      schema-locations: classpath:db/work_quill_base_schema.sql

  mvc:
    view:
      suffix: .html

  messages:
    basename: i18n/messages

  devtools:
    restart:
      enabled: false

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: WORK_QUILL

management:
  endpoint:
    nacosdiscovery:
      enabled: true

# Custom configuration
app:
  default-language: zh_CN
  base:
    api:
      prefix: /api
      username-login-path: /auth/login/username

  jwt:
    private-key: # Read from local file
    public-key: # Read from local file
    # minutes
    expire-time: 60
    refresh-time: 1480

